config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'sakes#index'
  get "/" => 'sakes#index'
  resources :sakes, only: [:index, :new]
  resources :aisakayas, only: [:index, :new]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sake.rb
class Sake < ApplicationRecord
end

app/controllers/aisakayas_controller.rb
class AisakayasController < ApplicationController
  def index
  end

  def new
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/sakes_controller.rb
class SakesController < ApplicationController
  def index
  end

  def new
  end
  
end

app/helpers/aisakayas_helper.rb
module AisakayasHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sakes_helper.rb
module SakesHelper
end

app/views/aisakayas/new.html.erb
<!DOCTYPE HTML>
<html>
  <head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="new.css">
    <title>相酒屋</title>
  </head>
  <body>
      <img src="https://vox.athome.co.jp/vox/wp-content/uploads/n5-kei-43-1.jpg" width="300px">
    <div class="text">
			<h2>相酒屋とは</h2>
  	</div>
    <div class="text2">
			<h2>相酒屋(あいさかや)は新たな好みのお酒との<br>出会いの場です。日本酒の繊細な味を言葉で<br>表すのは至難の業であり、もっと直感的に素<br>晴らしいお酒との出会いを果たして欲しいと<br>いう想いから作成しました。図のお好きな場<br>所をクリックするとおすすめのサイトに移動<br>します。素敵な出会いがありますように。</h2>
  	</div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Aisakaya35575</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layputs/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Aisakaya</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
    <%= yield %>
    <footer>
      <p>
        Copyright Aisakaya 2021.
      </p>
    </footer>
</html>

app/views/sakes/index.html.erb
<!DOCTYPE HTML>
<html>
  <head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="assets/index.css">
    <title>相酒屋</title>
  </head>

  <body>
    <div class="img">
    </div>
    <div class="title">
      <h1>相酒屋</h1>
    </div>
	  <div class="message">
      <h2>相酒屋は新たな好みのお酒との出会いの場です。</h2>
    </div>
    <div class="animation">
      <div class="effect"></div>
      <%= link_to '←入店する', new_sake_path %>
    </div>
  </body>
</html>

app/views/sakes/new.html.erb
<!DOCTYPE HTML>
<html>
  <head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="new.css">
    <title>相酒屋</title>
  </head>

	<div class="cp_cont">
		<div class="cp_offcm01">
			<input type="checkbox" id="cp_toggle01">
			<label for="cp_toggle01"><span></span></label>
			<div class="cp_menu">
			<ul>
			<li><%=link_to '相酒屋とは？', new_aisakaya_path %></li> 
			<%# <li><%=link_to '私のおすすめの酒', user_session_path</li>  %>
			<%# <li><%=link_to '飲んだお酒メモ', new_memo_path</li>  %>
			<%# <li><a href="#">menu4</a></li>
			<li><a href="#">menu5</a></li> %>
			</ul>
			</div>
		</div>
		<div class="title">
			<h1>-相酒屋-</h1>
  	</div>
  		<div class="content">
			<h1>お好きなポイントをクリックして下さい</h1>
  	</div>
  	<div class="img_block">
			<img src="https://img.furusato-tax.jp/img/x/stg/product/detail/details/20200910/spdd_330ef73978a23aa33c06b0ba7f8093b012b3b164.jpg" alt=”マトリックス” usemap="#image-map" >  
			<map name="image-map">
    		<area alt="1"  href="http://www.aramasa.jp/" coords="0,0,451,288" shape="rect">
    		<area alt="2"  href="http://www.kenbishi.co.jp/" coords="290,0,900,288" shape="rect">
    		<area alt="3"  href="http://www.heiwashuzou.co.jp/wordpress/" coords="0,290,451,576" shape="rect">
  	  	<area alt="4"  href="https://harukasumi.com/" coords="451,290,900,576" shape="rect">
	 		</map>
  	</div>
	</div>
</html>